import { PwaSettings } from './PwaSettings.js';
import { useState } from 'react';
import { Check, Copy, Download, LogOut, Monitor, Moon, RefreshCw, Sun, Unplug } from 'lucide-react';
import type { AppRuntime } from './runtime.js';
import { Modal, Notice } from './primitives.js';
import type { Theme } from './preferences.js';
import { connectionSummary } from '../src/hermes/connection-summary.js';

export function Settings({ runtime: rt, onClose, theme, setTheme }: { runtime: AppRuntime; onClose: () => void; theme: Theme; setTheme: (theme: Theme) => void }) {
  const [tab, setTab] = useState('connection'), [report, setReport] = useState(''), [note, setNote] = useState('');
  const state = rt.connection.state, busy = state.busy || state.offline, localAccess = rt.dashboard.admissionMode === 'trusted-local';
  const exportReport = () => { const text = JSON.stringify(rt.connection.report(), null, 2); setReport(text); return text; };
  return <Modal title="Settings" onClose={onClose}><div className="settings-tabs" role="tablist" aria-label="Settings sections">{['connection', 'appearance', 'diagnostics', 'app'].map(key => <button role="tab" id={`settings-tab-${key}`} aria-controls="settings-panel" tabIndex={tab === key ? 0 : -1} aria-selected={tab === key} key={key} onKeyDown={event => { if (["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) { event.preventDefault(); const tabs = ["connection", "appearance", "diagnostics", "app"], at = tabs.indexOf(key), next = event.key === "Home" ? 0 : event.key === "End" ? 3 : (at + (event.key === "ArrowRight" ? 1 : 3)) % 4; setTab(tabs[next]!); document.getElementById(`settings-tab-${tabs[next]}`)?.focus(); } }} onClick={() => setTab(key)}>{key[0]!.toUpperCase() + key.slice(1)}</button>)}</div>
    <div className="settings-body" id="settings-panel" role="tabpanel" aria-labelledby={`settings-tab-${tab}`} tabIndex={0}>
      {tab === 'app' && <PwaSettings runtime={rt}/>}
      {tab === 'connection' && <><h3>Your Hermes connection</h3><p className="muted">{connectionSummary(state, rt.gateway.state)}</p><dl className="connection-facts">
        <div><dt>Authentication</dt><dd data-testid="auth-state">{state.auth}</dd></div><div><dt>Dashboard REST</dt><dd>{state.rest}</dd></div><div><dt>Native Gateway</dt><dd data-testid="gateway-state">{rt.gateway.state.phase}</dd></div><div><dt>Active session</dt><dd>{rt.chat.native.state.phase}</dd></div><div><dt>Heartbeat</dt><dd>{rt.gateway.telemetry().latencyMs === undefined ? 'Not measured' : `${rt.gateway.telemetry().latencyMs} ms`}</dd></div>
      </dl><div className="button-row"><button className="primary" disabled={busy} onClick={() => rt.run(() => rt.connection.start())}><RefreshCw size={16}/>Reconnect</button><button className="secondary" disabled={busy} onClick={() => rt.connection.disconnect()}><Unplug size={16}/>Disconnect</button></div><p className="small muted">{localAccess ? "Disconnect pauses this tab only. This LAN address still has no login and remains available to others." : "Disconnect pauses this browser’s transport. It does not sign you out."}</p>
      <div className="settings-divider"/>{localAccess ? <Notice>Trusted-LAN access is explicitly enabled by the operator. There is no browser account to sign out of. Keep this service private; it is not safe for public-internet exposure.</Notice> : <button className="danger-text" disabled={busy} onClick={() => { rt.run(() => rt.connection.logout()); onClose(); }}><LogOut size={16}/>Sign out of Hermes</button>}</>}
      {tab === 'appearance' && <><h3>Make yourself at home</h3><p className="muted">Appearance is saved in this browser. Your conversations are not.</p><div className="theme-options">{([['system', Monitor, 'System'], ['light', Sun, 'Light'], ['dark', Moon, 'Dark']] as const).map(([value, Icon, label]) => <button key={value} className={theme === value ? 'active' : ''} aria-pressed={theme === value} onClick={() => setTheme(value)}><Icon size={25}/><span>{label}</span>{theme === value && <Check size={14}/>}</button>)}</div></>}
      {tab === 'diagnostics' && <><h3>Connection diagnostics</h3><p className="muted">Status, timings and capability flags only. No conversations, credentials or raw backend logs.</p><div className="button-row"><button className="secondary" onClick={() => rt.run(() => rt.connection.refreshCapabilities())}><RefreshCw size={15}/>Refresh capabilities</button><button className="secondary" onClick={() => { const text = exportReport(); if (!navigator.clipboard) { setNote('Select and copy the report below.'); return; } void navigator.clipboard.writeText(text).then(() => setNote('Report copied.')).catch(() => setNote('Select and copy the report below.')); }}><Copy size={15}/>Copy report</button><button className="secondary" onClick={() => { const url = URL.createObjectURL(new Blob([exportReport()], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'hermes-diagnostics.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}><Download size={15}/>Download</button></div>
      <details className="capability-details"><summary>Capability evidence</summary><dl className="connection-facts">{Object.entries(rt.connection.capabilities.snapshot()).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value.state}{!value.implemented && ' · not in UI'}</dd></div>)}</dl></details>
      <p className="small muted">{rt.diagnostics.snapshot().length} / 500 metadata entries in this tab.</p><button className="text-button" onClick={() => { rt.diagnostics.clear(); setReport(''); setNote('Diagnostic history cleared.'); rt.notify(); }}>Clear diagnostics</button>
      {report && <label className="field">Sanitised support report<textarea readOnly rows={7} value={report}/></label>}<p className="small" role="status">{note}</p></>}
      {rt.error && <Notice error>{rt.error}</Notice>}
    </div><footer className="settings-footer">HermesUI NG · Native Gateway client</footer></Modal>;
}
