import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../../server/app.js';
import { loadConfig } from '../../server/config.js';
import { DashboardClient } from '../../src/hermes/dashboard-client.js';
import { GatewayClient } from '../../src/hermes/gateway-client.js';
import { WsAuthClient } from '../../src/hermes/ws-auth.js';
import { ConnectionStore } from '../../src/hermes/connection-store.js';
import { ChatController } from '../../src/hermes/chat-controller.js';
import { SessionAttention } from '../../src/hermes/session-attention.js';
import { startFixture } from '../fixtures/dashboard.js';
import { browserAuth } from '../helpers/browser-auth.js';
for (const local of [false, true]) test(`synthetic M3 ${local ? 'local' : 'gated'}: pending inputs survive a switch and return over actual sockets`, async t => {
  const fixture = await startFixture(0, local ? { sessionToken: 'M3_ONLY_TEST_TOKEN' } : {});
  const config = loadConfig({ HERMES_DASHBOARD_URL: fixture.origin, PUBLIC_ORIGIN: 'http://127.0.0.1:1',
    ...(local ? { HERMES_AUTH_MODE: 'trusted-local', HERMES_DASHBOARD_SESSION_TOKEN: 'M3_ONLY_TEST_TOKEN' } : {}) });
  const logs: unknown[] = [], app = createApp(config, entry => logs.push(entry));
  await new Promise<void>(resolve => app.server.listen(0, '127.0.0.1', resolve));
  const address = app.server.address(); assert.ok(address && typeof address !== 'string');
  const origin = `http://127.0.0.1:${address.port}`; config.publicOrigin = new URL(origin);
  const browser = browserAuth(origin), dashboard = new DashboardClient(origin, browser.fetcher);
  const gateway = new GatewayClient(new WsAuthClient(dashboard, signal => connection.verifyAdmission(signal)), { socketFactory: browser.socketFactory, heartbeatMs: 0 });
  const connection: ConnectionStore = new ConnectionStore(dashboard, gateway);
  const chat = new ChatController(dashboard, gateway), attention = new SessionAttention(gateway);
  t.after(async () => { attention.dispose(); chat.dispose(); connection.dispose(); await app.close(); await fixture.close(); });
  await connection.start(); if (!local) await connection.login('basic', 'fixture', 'fixture-password');
  chat.setEnabled(true); attention.setEnabled(true);
  await chat.create('work'); const original = chat.native, ref = { ...chat.selected! };
  attention.bind(original.state.runtimeId!, ref);
  chat.setDraft('[agent-test] secret socket proof'); await chat.send();
  const poll = async (check: () => boolean) => { for (let i = 0; i < 200; i++) { if (check()) return; await new Promise(resolve => setTimeout(resolve, 10)); } throw new Error('M3 socket condition timed out'); };
  await poll(() => original.state.phase === 'waiting');
  const key = original.activity.state.inputs[0]!.key;
  await chat.create('default'); await attention.refresh();
  assert.equal(attention.forSession(ref)?.status, 'waiting');
  assert.equal(attention.forSession({ id: ref.id, profile: 'default' }), undefined);
  await assert.rejects(original.respond(key, 'NOT_PERMITTED_WHILE_HIDDEN'));
  await chat.open(ref); assert.equal(chat.native, original);
  await chat.native.respond(key, 'SECRET_TEST_VALUE'); await poll(() => chat.native.state.phase === 'idle');
  assert.equal(fixture.interactions.responseCounts.secret, 1);
  await assert.rejects(chat.native.respond(key, 'SECRET_TEST_VALUE'));
  assert.equal(fixture.interactions.responseCounts.secret, 1);
  assert.ok(!JSON.stringify([chat.native.state, chat.native.activity.state, chat.native.activity.archive, attention.items, connection.report(), logs]).includes('SECRET_TEST_VALUE'));
});
