import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../../server/app.js';
import { loadConfig } from '../../server/config.js';
import { DashboardClient } from '../../src/hermes/dashboard-client.js';
import { GatewayClient } from '../../src/hermes/gateway-client.js';
import { WsAuthClient } from '../../src/hermes/ws-auth.js';
import { ConnectionStore } from '../../src/hermes/connection-store.js';
import { NativeSession } from '../../src/hermes/native-session.js';
import { modelCatalogue } from '../../src/hermes/model-catalog.js';
import { startFixture } from '../fixtures/dashboard.js';
import { browserAuth } from '../helpers/browser-auth.js';
for (const local of [false, true]) test(`synthetic settings wire: ${local ? 'trusted-local' : 'gated'} native model/effort and profile isolation`, async t => {
  const token = 'FIXTURE_LOCAL_SETTING_TOKEN';
  const upstream = await startFixture(0, local ? { sessionToken: token } : {});
  const config = loadConfig({ HERMES_DASHBOARD_URL: upstream.origin, PUBLIC_ORIGIN: 'http://127.0.0.1:1',
    ...(local ? { HERMES_AUTH_MODE: 'trusted-local', HERMES_DASHBOARD_SESSION_TOKEN: token } : {}) });
  const logs: unknown[] = []; const app = createApp(config, event => logs.push(event));
  await new Promise<void>(resolve => app.server.listen(0, '127.0.0.1', resolve));
  const address = app.server.address(); assert.ok(address && typeof address !== 'string');
  const origin = `http://127.0.0.1:${address.port}`; config.publicOrigin = new URL(origin);
  const auth = browserAuth(origin), dashboard = new DashboardClient(origin, auth.fetcher);
  const gateway = new GatewayClient(new WsAuthClient(dashboard, (signal): Promise<void> => store.verifyAdmission(signal)), { socketFactory: auth.socketFactory, heartbeatMs: 0 });
  const store = new ConnectionStore(dashboard, gateway), first = new NativeSession(gateway), second = new NativeSession(gateway);
  t.after(async () => { first.dispose(); second.dispose(); store.dispose(); await app.close(); await upstream.close(); });
  await store.start(); if (!local) await store.login('basic', 'fixture', 'fixture-password');
  assert.equal(gateway.state.phase, 'ready');
  await first.create('default'); assert.equal(first.state.agent?.model, 'fixture-alpha');
  const options = modelCatalogue(await gateway.call('model.options', { session_id: first.state.runtimeId, profile: 'default' }));
  const beta = options.choices.find(row => row.model === 'fixture-beta')!;
  await first.settings.changeModel(beta); assert.equal(first.state.agent?.model, 'fixture-beta');
  await first.settings.changeReasoning('high'); assert.equal(first.state.agent?.reasoningEffort, 'high');
  const durable = first.state.storedId;
  await second.create('work'); assert.equal(second.state.agent?.model, 'work-model');
  assert.equal(second.state.agent?.reasoningEffort, 'low');
  assert.deepEqual(await gateway.call('config.get', { key: 'reasoning', profile: 'default' }), { value: 'medium', display: 'show' });
  await first.submit('Controlled settings prompt');
  for (let i = 0; first.state.phase !== 'idle' && i < 100; i++) await new Promise(resolve => setTimeout(resolve, 10));
  store.disconnect(); await store.start();
  for (let i = 0; first.state.phase !== 'idle' && i < 100; i++) await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(first.state.storedId, durable); assert.equal(first.state.agent?.model, 'fixture-beta');
  assert.equal(first.state.agent?.reasoningEffort, 'high'); assert.equal(upstream.metrics.submits, 1);
  assert.equal(second.state.agent?.model, 'work-model');
  const diagnostic = JSON.stringify(store.report()); assert.ok(!diagnostic.includes(token)); assert.ok(!diagnostic.includes('fixture-beta'));
  assert.ok(!JSON.stringify(logs).includes('Controlled settings prompt'));
});
